# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACText' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for RACText
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'Reachability', '~> 3.2'
  pod 'MBProgressHUD'
end
